from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd
import yfinance as yf


def load_symbols(path: Path) -> list[str]:
    symbols: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip().upper()
        if not line or line.startswith("#"):
            continue
        symbols.append(line)
    deduped = list(dict.fromkeys(symbols))
    if not deduped:
        raise ValueError(f"No symbols found in {path}")
    return deduped


@dataclass
class StockLiquidity:
    symbol: str
    avg_daily_share_volume: float
    avg_daily_dollar_volume: float
    trading_days: int


@dataclass
class EtfSize:
    symbol: str
    total_assets: float


def fetch_stock_liquidity(symbol: str, start: pd.Timestamp, end: pd.Timestamp) -> StockLiquidity | None:
    try:
        history = yf.Ticker(symbol).history(
            start=start,
            end=end,
            interval="1d",
            auto_adjust=False,
            actions=False,
        )
    except Exception:
        return None

    if history.empty or "Volume" not in history.columns or "Close" not in history.columns:
        return None

    history = history.dropna(subset=["Volume", "Close"])
    if history.empty:
        return None

    avg_share_volume = float(history["Volume"].mean())
    avg_dollar_volume = float((history["Volume"] * history["Close"]).mean())
    return StockLiquidity(
        symbol=symbol,
        avg_daily_share_volume=avg_share_volume,
        avg_daily_dollar_volume=avg_dollar_volume,
        trading_days=len(history),
    )


def fetch_etf_assets(symbol: str) -> EtfSize | None:
    try:
        info = yf.Ticker(symbol).info
    except Exception:
        return None

    total_assets = info.get("totalAssets")
    if total_assets is None:
        total_assets = info.get("fundAssets")
    if total_assets is None:
        total_assets = info.get("netAssets")
    if total_assets is None:
        return None

    try:
        assets_value = float(total_assets)
    except Exception:
        return None
    if assets_value <= 0:
        return None

    return EtfSize(symbol=symbol, total_assets=assets_value)


def rank_stocks(candidates: Iterable[str], start: pd.Timestamp, end: pd.Timestamp, top_n: int) -> pd.DataFrame:
    rows: list[StockLiquidity] = []
    for symbol in candidates:
        result = fetch_stock_liquidity(symbol, start=start, end=end)
        if result is not None:
            rows.append(result)

    if not rows:
        raise RuntimeError("No stock liquidity data returned. Check network access or candidate symbols.")

    frame = pd.DataFrame([r.__dict__ for r in rows])
    frame = frame.sort_values(
        ["avg_daily_share_volume", "avg_daily_dollar_volume"],
        ascending=[False, False],
    ).reset_index(drop=True)
    return frame.head(top_n)


def rank_etfs(candidates: Iterable[str], top_n: int) -> pd.DataFrame:
    rows: list[EtfSize] = []
    for symbol in candidates:
        result = fetch_etf_assets(symbol)
        if result is not None:
            rows.append(result)

    if not rows:
        raise RuntimeError("No ETF asset data returned. Check network access or candidate symbols.")

    frame = pd.DataFrame([r.__dict__ for r in rows])
    frame = frame.sort_values("total_assets", ascending=False).reset_index(drop=True)
    return frame.head(top_n)


def write_ticker_file(
    output_path: Path,
    stocks: pd.DataFrame,
    etfs: pd.DataFrame,
    start: pd.Timestamp,
    end: pd.Timestamp,
) -> None:
    lines: list[str] = []
    lines.append(
        f"# Auto-generated by scripts/update_universe.py on {pd.Timestamp.now(tz='UTC').strftime('%Y-%m-%d %H:%M UTC')}"
    )
    lines.append(f"# Stocks ranked by average daily share volume from {start.date()} to {end.date()}")
    for symbol in stocks["symbol"].tolist():
        lines.append(symbol)
    lines.append("")
    lines.append("# ETFs ranked by latest total assets (AUM proxy)")
    for symbol in etfs["symbol"].tolist():
        lines.append(symbol)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_audit(output_dir: Path, stocks: pd.DataFrame, etfs: pd.DataFrame) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    stock_path = output_dir / "universe_stocks_ranked.csv"
    etf_path = output_dir / "universe_etfs_ranked.csv"
    stocks.to_csv(stock_path, index=False)
    etfs.to_csv(etf_path, index=False)
    return stock_path, etf_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Recompute ticker universe for stock picker.")
    parser.add_argument("--stock-candidates-file", type=Path, default=Path("universe/stock_candidates.txt"))
    parser.add_argument("--etf-candidates-file", type=Path, default=Path("universe/etf_candidates.txt"))
    parser.add_argument("--output-tickers-file", type=Path, default=Path("tickers.txt"))
    parser.add_argument("--audit-dir", type=Path, default=Path("local_data/audit"))
    parser.add_argument("--stock-top-n", type=int, default=20)
    parser.add_argument("--etf-top-n", type=int, default=20)
    parser.add_argument("--stock-lookback-years", type=int, default=2)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    end = pd.Timestamp.now(tz="UTC")
    start = end - pd.DateOffset(years=args.stock_lookback_years)

    stock_candidates = load_symbols(args.stock_candidates_file)
    etf_candidates = load_symbols(args.etf_candidates_file)

    stocks = rank_stocks(stock_candidates, start=start, end=end, top_n=args.stock_top_n)
    etfs = rank_etfs(etf_candidates, top_n=args.etf_top_n)

    write_ticker_file(args.output_tickers_file, stocks=stocks, etfs=etfs, start=start, end=end)
    stock_audit, etf_audit = write_audit(args.audit_dir, stocks=stocks, etfs=etfs)

    print(f"Wrote {len(stocks)} stock symbols and {len(etfs)} ETF symbols to {args.output_tickers_file}")
    print(f"Stock ranking audit: {stock_audit}")
    print(f"ETF ranking audit: {etf_audit}")


if __name__ == "__main__":
    main()
